import random

"""
In this game, the computer guesses a number generated by the user.

If the computer guesses a number that is too high, the user prompts the computer
by telling it that it guessed too high. If the computer guesses a number that is
too low, the user prompts the computer by telling it that it guessed too low. Using
these prompts, the computer continues to guess until it guesses the number generated
by the user.
"""

def computer_guess(x):
    low = 1
    high = x
    feedback = ''
    while feedback != 'c':
        if low != high:
            guess = random.randint(low, high)
        else:
            guess = low
        feedback = input(f"Is {guess} too high (H), too low (L), or correct (C)? ").lower()
        if feedback == 'h':
            high = guess - 1
        elif feedback == 'l':
            low = guess + 1
    print(f"Yay! The computer guessed your number, {guess}, correctly!")
